/*
 * This source file was generated by the Gradle 'init' task
 */
package bcc.swinggame;
import java.awt.Image;

public class plane {
    protected int x;
    protected int y;
    protected int width;
    protected int height;
    //angle is changed by +/- 45 degrees every time you press right/left or d/a
    protected int angle;
    protected boolean inverted;
    protected int xvelocity;
    protected int yvelocity;
    protected int ammoWidth;
    protected int ammoHeight;
    protected int ammoX;
    protected int ammoY;
    protected int health;
    protected Image url;

    public plane(int x, int y, int width, int height, int angle, int xvelocity, int yvelocity, int ammoWidth, int ammoHeight, int ammoX, int ammoY, Image url) {
        this.x = x;
        this.y = y;
        this.width = width;
        this.height = height;
        this.angle = angle;
        this.inverted = false;
        this.xvelocity = xvelocity;
        this.yvelocity = yvelocity;
        this.ammoWidth = ammoWidth;
        this.ammoHeight = ammoHeight;
        this.ammoX = ammoX;
        this.ammoY = ammoY;
        this.health = 1;
        this.url = url;
    }
    
    public boolean isAlive() {
        if(health <= 0){
            return false;
        }
        else{
            return true;
        }
    }
    public void hit() {
        health = 0;
    }
    public int getX() { return x; }
    public int getY() { return y; }
    public int getWidth() { return width; }
    public int getHeight() { return height; }
}
